{% set name = "cuda-nvdisasm" %}
{% set version = "13.4.92" %}
{% set cuda_version = "13.4" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-ppc64le" %}  # [ppc64le]
{% set platform = "linux-sbsa" %}  # [aarch64]
{% set platform = "windows-x86_64" %}  # [win64]
{% set platform = "windows-arm64" %}  # [win and arm64]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]
{% set sha256 = "d0af2b49c3ba6b4f64f3e284e0229d234aa88beeba8e033a8a4fe5db7c4cc3b6" %}  # [linux64]
{% set sha256 = "7959183e0ac67c6089fddc9e5e6c0104f68c7ed66d3d9707b5816ac800d5ea1c" %}  # [aarch64]
{% set sha256 = "42a08d81ea1b70ff5f75914733ccfd236d7be01b8df8e408c894d57f11bf68fa" %}  # [win64]
{% set sha256 = "4d37163666b114c9a2d118314da2a5e977ae0cc4edb555c96675f0a2e1573e4f" %}  # [win and arm64]

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_nvdisasm/{{ platform }}/cuda_nvdisasm-{{ platform }}-{{ version }}-archive.{{ extension }}
  sha256: {{ sha256 }}

build:
  number: 0
  binary_relocation: false
  skip: true  # [osx or ppc64le]
  script:
    - move bin\* %LIBRARY_BIN%  # [win]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - arm-variant * {{ arm_variant_type }}  # [aarch64]
    - cf-nvidia-tools 1  # [linux]
  host:
    - cuda-version {{ cuda_version }}
  run:
    - {{ pin_compatible("cuda-version", max_pin="x.x") }}
  run_constrained:
    - arm-variant * {{ arm_variant_type }}  # [aarch64]

test:
  requires:
    - patchelf                                        # [linux]
  files:
    - test-rpath.sh                                   # [linux]
  commands:
    - test -f $PREFIX/bin/nvdisasm                    # [linux]
    - bash test-rpath.sh                              # [linux]
    - if not exist %LIBRARY_BIN%\nvdisasm.exe exit 1  # [win]

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: nvdisasm extracts information from standalone cubin files
  description: |
    nvdisasm extracts information from standalone cubin files and presents them in
    human readable format.
  doc_url: https://docs.nvidia.com/cuda/cuda-binary-utilities/

extra:
  recipe-maintainers:
    - conda-forge/cuda
